#!/usr/bin/env python3
"""Compile the intentionally small SwapScript .swp format into a C header."""
import argparse
import math
import re
import struct
from pathlib import Path

IDENT = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")
RULE = re.compile(r"^transition\s+(\w+)\s*->\s*(\w+)\s+when\s+(\w+)\s*(<=|>=|==|!=|<|>)\s*(-?(?:\d+(?:\.\d*)?|\.\d+)(?:[eE][+-]?\d+)?)\s+hold\s+(\d+)\s*ms$")

def fnv1a(text: str) -> int:
    h = 2166136261
    for byte in text.encode("utf-8"):
        h = ((h ^ byte) * 16777619) & 0xffffffff
    return h

def compile_source(source: str, max_contexts: int = 16, max_metrics: int = 32) -> str:
    if max_contexts < 1 or max_metrics < 1:
        raise ValueError("capacity limits must be positive")
    contexts, metrics, rules = [], set(), []
    initial = None
    for number, raw in enumerate(source.splitlines(), 1):
        line = raw.split("#", 1)[0].strip()
        if not line: continue
        parts = line.split()
        if parts[0] == "context" and len(parts) == 4 and parts[2] == "params":
            _, name, _, symbol = parts
            if not IDENT.fullmatch(name) or not IDENT.fullmatch(symbol): raise ValueError(f"line {number}: invalid identifier")
            if name in [c[0] for c in contexts]: raise ValueError(f"line {number}: duplicate context {name}")
            contexts.append((name, symbol))
        elif parts[0] == "initial" and len(parts) == 2:
            if initial is not None: raise ValueError(f"line {number}: duplicate initial declaration")
            initial = parts[1]
        else:
            match = RULE.fullmatch(line)
            if not match: raise ValueError(f"line {number}: unrecognized statement")
            src, dst, metric, op, threshold, hold = match.groups()
            if not IDENT.fullmatch(metric): raise ValueError(f"line {number}: invalid metric identifier")
            threshold_value = float(threshold)
            hold_value = int(hold)
            if not math.isfinite(threshold_value) or abs(threshold_value) > 3.402823466e38:
                raise ValueError(f"line {number}: threshold must fit a finite C float")
            try:
                rounded_threshold = struct.unpack(">f", struct.pack(">f", threshold_value))[0]
            except OverflowError as exc:
                raise ValueError(f"line {number}: threshold must fit a finite C float") from exc
            if threshold_value != 0.0 and rounded_threshold == 0.0:
                raise ValueError(f"line {number}: threshold is too small for a C float")
            threshold = format(rounded_threshold, ".9g")
            if hold_value > 2147483647:
                raise ValueError(f"line {number}: hold must be less than 2^31 milliseconds")
            rules.append((src, dst, metric, op, threshold, hold_value))
            metrics.add(metric)
    names = {c[0] for c in contexts}
    if not contexts: raise ValueError("declare at least one context")
    if not rules: raise ValueError("declare at least one transition")
    if len(contexts) > max_contexts: raise ValueError(f"context count exceeds capacity {max_contexts}")
    if len(metrics) > max_metrics: raise ValueError(f"metric count exceeds capacity {max_metrics}")
    if initial not in names: raise ValueError("initial must name a declared context")
    for src, dst, *_ in rules:
        if src not in names or dst not in names or src == dst: raise ValueError(f"invalid transition {src} -> {dst}")
    ids = {name: fnv1a(name) for name, _ in contexts}
    keys = {name: fnv1a(name) for name in metrics}
    if len(set(ids.values())) != len(ids): raise ValueError("context ID hash collision")
    if len(set(keys.values())) != len(keys): raise ValueError("metric key hash collision")
    for namespace in ([name for name, _ in contexts], list(metrics)):
        macro_names = [name.upper() for name in namespace]
        if len(set(macro_names)) != len(macro_names): raise ValueError("names collide after C macro uppercasing")
    out = ["/* Generated by SwapScript compiler.py; do not edit. */", "#ifndef SWAPSCRIPT_GENERATED_H", "#define SWAPSCRIPT_GENERATED_H", "#include \"swapscript.h\"", ""]
    for name, symbol in contexts: out.append(f"#define SS_CONTEXT_{name.upper()} 0x{ids[name]:08x}u")
    for name in sorted(metrics): out.append(f"#define SS_METRIC_{name.upper()} 0x{keys[name]:08x}u")
    out += ["", "static const ss_rule_t ss_generated_rules[] = {"]
    for src, dst, metric, op, threshold, hold in rules:
        number = format(float(threshold), ".9g")
        if "." not in number and "e" not in number.lower(): number += ".0"
        out.append(f"    {{SS_CONTEXT_{src.upper()}, SS_CONTEXT_{dst.upper()}, SS_METRIC_{metric.upper()}, {number}f, {hold}u, SS_{ {'<':'LT','<=':'LE','>':'GT','>=':'GE','==':'EQ','!=':'NE'}[op]}}},")
    out += ["};", f"#define SS_GENERATED_RULE_COUNT {len(rules)}u", f"#define SS_INITIAL_CONTEXT SS_CONTEXT_{initial.upper()}", "", "#endif"]
    return "\n".join(out) + "\n"

def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("input", type=Path)
    parser.add_argument("-o", "--output", type=Path, default=Path("swapscript_generated.h"))
    parser.add_argument("--max-contexts", type=int, default=16, help="must match SS_MAX_CONTEXTS")
    parser.add_argument("--max-metrics", type=int, default=32, help="must match SS_MAX_METRICS")
    args = parser.parse_args()
    try:
        compiled = compile_source(args.input.read_text(encoding="utf-8"), args.max_contexts, args.max_metrics)
    except (OSError, ValueError) as exc:
        parser.error(str(exc))
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(compiled, encoding="utf-8")
    print(f"Wrote {args.output}")

if __name__ == "__main__": main()
