/* Generated by SwapScript compiler.py; do not edit. */
#ifndef SWAPSCRIPT_GENERATED_H
#define SWAPSCRIPT_GENERATED_H
#include "swapscript.h"

#define SS_CONTEXT_DAYLIGHT 0x30da2927u
#define SS_CONTEXT_NIGHT 0xe6de9f61u
#define SS_METRIC_AMBIENT_LUX 0x9601af05u

static const ss_rule_t ss_generated_rules[] = {
    {SS_CONTEXT_DAYLIGHT, SS_CONTEXT_NIGHT, SS_METRIC_AMBIENT_LUX, 20.0f, 50u, SS_LE},
    {SS_CONTEXT_NIGHT, SS_CONTEXT_DAYLIGHT, SS_METRIC_AMBIENT_LUX, 30.0f, 100u, SS_GE},
};
#define SS_GENERATED_RULE_COUNT 2u
#define SS_INITIAL_CONTEXT SS_CONTEXT_DAYLIGHT

#endif
